plugins {
    id 'java'
    id 'jacoco'
    id 'maven-publish'
    alias(libs.plugins.enonic.defaults)
    id 'com.enonic.xp.base'
}

repositories {
    mavenCentral()
    xp.enonicRepo('dev')
}

dependencies {
    compileOnly xplibs.api.script
    compileOnly "com.enonic.xp:core-api:${xpVersion}"
    testImplementation "com.enonic.xp:testing:${xpVersion}"
    testImplementation libs.osgi.core

    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly  libs.junit.launcher

    testImplementation platform(libs.mockito.bom)
    testImplementation libs.mockito.core
    testImplementation libs.mockito.jupiter
    testImplementation libs.assertj.core

    testRuntimeOnly libs.graalvm.js
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}

check.dependsOn jacocoTestReport

artifacts {
    archives jar
}

test {
    useJUnitPlatform()
}

def testGraalJs = tasks.register('testGraalJs', Test) {
    group = 'verification'
    description = 'Runs tests with the GraalJS script engine.'
    useJUnitPlatform()
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    systemProperty 'xp.script-engine', 'GraalJS'
    shouldRunAfter test
}

check.dependsOn testGraalJs
