= Cache Library

This library is used for basic caching of resources in memory. It will automatically evict old
entries when the cache is full. To start using this library, put the following into your `build.gradle`
file:

[source,groovy]
----
dependencies {
  include 'com.enonic.lib:lib-cache:2.1.0'
}
----

== Usage

To use this library in your JavaScript code, you first need to require it in your *controller*:

[source,js]
----
var cacheLib = require('/lib/cache');
----

Then you will need to create a new cache with some settings. You can create multiple caches in your
application.

WARNING: With the way XP triggers your controller, the new cache needs to be created *outside* the scope of any exported request handler. If it is created inside, for example, `exports.get()`, you will only create a temporary cache on each request.

[source,js]
----
var cache = cacheLib.newCache({
    size:   100,     <1>
    expire: 3600     <2>
});
----
<1> Maximum number of items in the cache before it will evict the oldest.
<2> Number of seconds the items will be in the cache before it's evicted.

From here on you can now use the cache functions on the cache. To get (or populate if not exists) items
you can do like this:

[source,js]
----
var item = cache.get('my-key', function() {     <1>
    return fetchSomethingHeavy();               <2>
});
----
<1> Get function will either get the item if exists, or call the function to populate the cache.
<2> Here you will do the actual population of the cache entry.


== API

Here's the API methods that is defined in this library.

=== `newCache`

This will create a new cache instance.

*Parameters*

* `config` (_object_) Configuration for the cache.
** `size` (_number_) Size of the cache (in number of items).
** `expire` (_number_) Expire time in number of seconds.

*Examples*

[source,js]
----
var cache = cacheLib.newCache({
    size:   100,
    expire: 3600
});
----


=== `Cache.get`

This function will get (or populate) the named item from cache.

*Parameters*

* `key` (_string_) Cache key to get.
* `fetcher` (_function_) Function to call if item does not exists. This needs to return what to cache.

*Examples*

[source,js]
----
var item = cache.get('my-key', function() {
    return fetchSomethingHeavy();
});
----


=== `Cache.clear`

This will clear all entries from the cache.

*Examples*

[source,js]
----
cache.clear();
----


=== `Cache.getSize`

This will return the number of items currently in the cache.

*Examples*

[source,js]
----
var size = cache.getSize();
----


=== `Cache.remove`

Removes an entry, identified by its key, from the cache.
If the key is not found in the cache, no changes are made.

*Parameter*

* `key` (_string_) Cache key to remove.

*Examples*

[source,js]
----
cache.remove('my-key');
----


=== `Cache.removePattern`

Removes multiple entries, identified by a regular expression, from the cache.
If the regex pattern does not match with any existing key, no changes are made.

*Parameter*

* `keyRegex` (_string_) Regular expression pattern to match with keys to be removed.

*Examples*

[source,js]
----
cache.removePattern('product.*');
----


== Compatibility

This library is also a drop-in replacement for the library in Enonic XP released before 6.11.0. It can be used directly since
it will work by using `/lib/cache`, `/lib/xp/cache` and `/site/lib/xp/cache`.

The `remove` and `removePattern` functions are only available since version *1.1.0*
